/* Script de criação de tabelas */

DROP DATABASE basePantry;
CREATE DATABASE basePantry;
use basePantry;

/* TABELA CATEGORIES */
CREATE TABLE Categories(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL,createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP NOT NULL);

/* TABELA PRODUCTS */
CREATE TABLE Products(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL UNIQUE, idCategory INT NOT NULL, CONSTRAINT fk_idCategory FOREIGN KEY(idCategory) REFERENCES Categories(id), createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP NOT NULL);

/* TABELA USERS */
CREATE TABLE Users(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, token VARCHAR(255), createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP NOT NULL);

/* TABELA PANTRIES */
CREATE TABLE Pantries(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL UNIQUE, shared BOOLEAN NOT NULL DEFAULT false, idOwner INT NOT NULL, CONSTRAINT fk_idOwner FOREIGN KEY(idOwner) REFERENCES Users(id),createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP NOT NULL);

/* TABELA SHARED PANTRIES */
CREATE TABLE SharedPantries(idPantry INT NOT NULL, idUser INT NOT NULL, CONSTRAINT pk_composite_key PRIMARY KEY (idPantry,idUser), CONSTRAINT fk_idPantry FOREIGN KEY(idPantry) REFERENCES Pantries(id),CONSTRAINT fk_idUser FOREIGN KEY(idUser) REFERENCES Users(id),createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP NOT NULL);

/* TABELA PANTRY PRODUCTS*/
CREATE TABLE PantryProducts(idPantry INT NOT NULL, idProduct INT NOT NULL, validity DATE NOT NULL, amount int NOT NULL, CONSTRAINT pk_composite_key PRIMARY KEY (idPantry,idProduct), CONSTRAINT fk_idPantries FOREIGN KEY(idPantry) REFERENCES Pantries(id), CONSTRAINT fk_idProduct FOREIGN KEY(idProduct) REFERENCES Products(id),createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP NOT NULL);
